nelmio_api_doc:
    documentation:
        servers:
            #- url: http://127.0.0.1:8000
            - url: https://engine.mosaic-ci.com

        info:
            title: "Engine"
            description: "API pour gérer les moteurs et les méthodes de calcul."
            version: "1.0.0"
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        default:
            path_patterns:
                - ^/api  # ✅ Tes routes commencent par /admin
